"""
Telegram Bot API transport — the SEND half of the approval loop's human step.

execution/approval_loop.py has always been able to *format* a proposal a human
could read on a phone; it had no way to actually put it on one. This module is
that wire, and nothing more: it can push text into a chat and it can read back
enough of getUpdates to discover a chat id during setup.

DELIBERATELY SEND-ONLY. There is no reply parsing, no approve/reject grammar,
no polling loop here. approval_loop.request_approvals — the function that would
turn a chat reply into an order — is still a stub, and this module gives it
nothing it could be built out of by accident. Approval remains a local,
console-side act. That boundary is the point: a message arriving on a phone is
a notification, and a notification cannot trade.

Also deliberately dependency-free of the rest of execution/: this module
imports settings and requests, and nothing that knows what a broker is. It is
structurally incapable of placing an order.

No new libraries. data/ingest/http.py's polygon_get is the repo's other HTTP
retry helper, but it is a GET with Polygon's quota baked into its pacing and
its log lines; Bot API calls are POSTs whose 429s carry their own
`parameters.retry_after`. Same shape, honestly reimplemented, rather than a
shared helper that lies about which vendor it is talking to.

The bot token is a bearer credential that lives in the URL path. It is never
logged and never put into an exception message — see _endpoint.
"""
from __future__ import annotations

import logging
import time

import requests

from config.settings import settings

logger = logging.getLogger(__name__)

API_BASE = "https://api.telegram.org"

DEFAULT_TIMEOUT = 15
DEFAULT_RETRY_AFTER = 3.0
DEFAULT_MAX_RETRIES = 3

# Bot API hard limit for a sendMessage body. Exceeding it is a 400, so a long
# batch gets trimmed here rather than failing to arrive at all.
MAX_MESSAGE_CHARS = 4096
TRUNCATION_NOTE = "\n\n[...trimmed — too long for one Telegram message]"

MISSING_TOKEN_MESSAGE = (
    "TELEGRAM_BOT_TOKEN is not set — nothing was sent.\n"
    "Get one by messaging @BotFather on Telegram (/newbot), then put the token "
    "in .env as TELEGRAM_BOT_TOKEN=..."
)

MISSING_CHAT_ID_MESSAGE = (
    "TELEGRAM_CHAT_ID is not set — nothing was sent.\n"
    "Send your bot any message on Telegram, then run:\n"
    "  python -m execution.approval_loop --telegram-setup\n"
    "and copy the chat id it prints into .env as TELEGRAM_CHAT_ID=..."
)


class TelegramError(RuntimeError):
    """
    Telegram was reachable but refused the call, or kept rate-limiting it.

    Carries only the method name and Telegram's own description — never the
    URL, which contains the bot token.
    """


def credentials(token: str | None = None, chat_id: str | None = None) -> tuple[str, str]:
    """
    Resolve (token, chat_id), explicit arguments winning over .env. Returned
    stripped, because a trailing space pasted out of BotFather turns into a
    404 that looks like a wrong token.
    """
    resolved_token = token if token is not None else settings.telegram_bot_token
    resolved_chat = chat_id if chat_id is not None else settings.telegram_chat_id
    return str(resolved_token or "").strip(), str(resolved_chat or "").strip()


def _endpoint(token: str, method: str) -> str:
    """
    The one place the token is interpolated into a string. Whatever this
    returns must not reach a log, an exception, or stdout.
    """
    return f"{API_BASE}/bot{token}/{method}"


def _retry_after_seconds(resp) -> float:
    """
    How long a 429 wants us to wait. Telegram puts it in the JSON body as
    parameters.retry_after; the Retry-After header is the fallback for a 429
    generated by something in front of the API rather than the API itself.
    """
    try:
        body = resp.json()
    except Exception:
        # A 429 generated by a proxy in front of the API is often not JSON at all.
        body = {}
    if isinstance(body, dict):
        parameters = body.get("parameters")
        if isinstance(parameters, dict) and parameters.get("retry_after") is not None:
            return float(parameters["retry_after"])
    return float(resp.headers.get("Retry-After", DEFAULT_RETRY_AFTER))


def call(
    method: str,
    token: str,
    payload: dict | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    max_retries: int = DEFAULT_MAX_RETRIES,
) -> dict:
    """
    POST one Bot API method and return its `result` field.

    Telegram answers errors with a 4xx *and* a JSON body containing a human
    description ("chat not found", "Unauthorized"). Those descriptions are the
    only useful diagnostic when setup goes wrong, so this reads the body rather
    than letting raise_for_status throw the status code away.
    """
    url = _endpoint(token, method)
    for attempt in range(1, max_retries + 1):
        try:
            resp = requests.post(url, json=payload or {}, timeout=timeout)
        except requests.RequestException as exc:
            # Wrapped rather than propagated so callers have exactly one
            # exception type to handle, and so the failed URL — which carries
            # the bot token — cannot ride out inside a requests exception.
            raise TelegramError(f"{method}: could not reach api.telegram.org ({type(exc).__name__})") from None

        if resp.status_code == 429:
            wait = _retry_after_seconds(resp)
            logger.warning(
                "Telegram rate limit on %s (attempt %s/%s) — sleeping %ss", method, attempt, max_retries, wait
            )
            time.sleep(wait)
            continue

        try:
            body = resp.json()
        except Exception as exc:
            raise TelegramError(f"{method}: HTTP {resp.status_code} with a non-JSON body") from exc

        if not isinstance(body, dict) or not body.get("ok"):
            description = ""
            if isinstance(body, dict):
                description = str(body.get("description", ""))
            raise TelegramError(f"{method}: HTTP {resp.status_code} — {description or 'call rejected'}")

        return body.get("result")

    raise TelegramError(f"{method}: still rate-limited after {max_retries} attempts")


def _clip(text: str) -> str:
    """One message means one message; a 4097-character batch is trimmed, not dropped."""
    if len(text) <= MAX_MESSAGE_CHARS:
        return text
    logger.warning("Telegram message is %s chars — trimming to %s.", len(text), MAX_MESSAGE_CHARS)
    return text[: MAX_MESSAGE_CHARS - len(TRUNCATION_NOTE)] + TRUNCATION_NOTE


def send_message(
    text: str,
    token: str | None = None,
    chat_id: str | None = None,
    call_fn=call,
) -> dict:
    """
    Put `text` in the configured chat as plain text.

    parse_mode is deliberately not set. The proposal strings carry %, +, -, |
    and _ characters that Markdown and HTML modes would either mangle or reject
    outright, and escaping rules have no business leaking back into the
    formatting code in approval_loop.py.

    Raises TelegramError if credentials are missing — callers that want the
    friendly "not configured, carrying on" behaviour check configured() first.
    """
    resolved_token, resolved_chat = credentials(token, chat_id)
    if not resolved_token:
        raise TelegramError("sendMessage: no bot token configured")
    if not resolved_chat:
        raise TelegramError("sendMessage: no chat id configured")

    logger.info("Sending %s chars to Telegram chat %s.", len(text), resolved_chat)
    return call_fn(
        "sendMessage",
        resolved_token,
        {"chat_id": resolved_chat, "text": _clip(text), "disable_web_page_preview": True},
    )


def fetch_updates(token: str | None = None, limit: int = 100, call_fn=call) -> list[dict]:
    """
    Recent updates for the bot — the raw material for chat-id discovery.

    No offset and no long-poll timeout: this must not consume updates or block,
    it just looks at what is already queued. Telegram keeps unretrieved updates
    for about 24 hours, which is why setup asks the user to message the bot
    first rather than assuming an old conversation is still visible.
    """
    resolved_token, _ = credentials(token, "")
    if not resolved_token:
        raise TelegramError("getUpdates: no bot token configured")
    result = call_fn("getUpdates", resolved_token, {"limit": limit, "timeout": 0})
    return list(result or [])


def chat_candidates(updates: list[dict]) -> list[dict]:
    """
    Distinct chats seen in `updates`, newest first, as
    {"chat_id", "name", "kind", "text"}.

    Newest first because the chat the user just messaged from is the one they
    are trying to find; older ones are noise from previous experiments.
    Deduplicated by chat id so a five-message conversation offers one answer,
    not five identical ones.
    """
    seen: dict[str, dict] = {}
    for update in reversed(list(updates)):
        message = None
        for key in ("message", "edited_message", "channel_post", "edited_channel_post"):
            candidate = update.get(key) if isinstance(update, dict) else None
            if isinstance(candidate, dict):
                message = candidate
                break
        if not message:
            continue

        chat = message.get("chat")
        if not isinstance(chat, dict) or chat.get("id") is None:
            continue

        chat_id = str(chat["id"])
        if chat_id in seen:
            continue

        name = (
            chat.get("title")
            or " ".join(p for p in (chat.get("first_name"), chat.get("last_name")) if p)
            or chat.get("username")
            or "(no name)"
        )
        seen[chat_id] = {
            "chat_id": chat_id,
            "name": str(name),
            "kind": str(chat.get("type", "unknown")),
            "text": str(message.get("text", "")),
        }
    return list(seen.values())
