"""
Telegram Bot API transport — the wire under execution/approval_gate.py.

approval_gate.py formats the numbered trade proposals, decides what a reply
means, and enforces the fail-closed rules; this module is only the transport
underneath it: push text into a chat, read raw getUpdates back (for reply
polling and for chat-id discovery during setup), and nothing else.

TRANSPORT ONLY. There is no reply parsing, no approve/reject grammar, and no
polling loop here — all of that lives in approval_gate.py, where it is tested
against the fail-closed rules. This module hands back raw updates and filtered
plain-text replies (replies_from); deciding that a reply approves a trade is
the gate's business alone.

Also deliberately dependency-free of the rest of execution/: this module
imports settings and requests, and nothing that knows what a broker is. It is
structurally incapable of placing an order.

Setup (one-time chat-id discovery):
    python -m execution.telegram --setup

No new libraries. data/ingest/http.py's polygon_get is the repo's other HTTP
retry helper, but it is a GET with Polygon's quota baked into its pacing and
its log lines; Bot API calls are POSTs whose 429s carry their own
`parameters.retry_after`. Same shape, honestly reimplemented, rather than a
shared helper that lies about which vendor it is talking to.

The bot token is a bearer credential that lives in the URL path. It is never
logged and never put into an exception message — see _endpoint.
"""
from __future__ import annotations

import logging
import time

import requests

from config.settings import settings

logger = logging.getLogger(__name__)

API_BASE = "https://api.telegram.org"

DEFAULT_TIMEOUT = 15
DEFAULT_RETRY_AFTER = 3.0
DEFAULT_MAX_RETRIES = 3

# Bot API hard limit for a sendMessage body. Exceeding it is a 400, so a long
# batch gets trimmed here rather than failing to arrive at all.
MAX_MESSAGE_CHARS = 4096
TRUNCATION_NOTE = "\n\n[...trimmed — too long for one Telegram message]"

MISSING_TOKEN_MESSAGE = (
    "TELEGRAM_BOT_TOKEN is not set — nothing was sent.\n"
    "Get one by messaging @BotFather on Telegram (/newbot), then put the token "
    "in .env as TELEGRAM_BOT_TOKEN=..."
)

MISSING_CHAT_ID_MESSAGE = (
    "TELEGRAM_CHAT_ID is not set — nothing was sent.\n"
    "Send your bot any message on Telegram, then run:\n"
    "  python -m execution.telegram --setup\n"
    "and copy the chat id it prints into .env as TELEGRAM_CHAT_ID=..."
)


class TelegramError(RuntimeError):
    """
    Telegram was reachable but refused the call, or kept rate-limiting it.

    Carries only the method name and Telegram's own description — never the
    URL, which contains the bot token.
    """


def credentials(token: str | None = None, chat_id: str | None = None) -> tuple[str, str]:
    """
    Resolve (token, chat_id), explicit arguments winning over .env. Returned
    stripped, because a trailing space pasted out of BotFather turns into a
    404 that looks like a wrong token.
    """
    resolved_token = token if token is not None else settings.telegram_bot_token
    resolved_chat = chat_id if chat_id is not None else settings.telegram_chat_id
    return str(resolved_token or "").strip(), str(resolved_chat or "").strip()


def _endpoint(token: str, method: str) -> str:
    """
    The one place the token is interpolated into a string. Whatever this
    returns must not reach a log, an exception, or stdout.
    """
    return f"{API_BASE}/bot{token}/{method}"


def _retry_after_seconds(resp) -> float:
    """
    How long a 429 wants us to wait. Telegram puts it in the JSON body as
    parameters.retry_after; the Retry-After header is the fallback for a 429
    generated by something in front of the API rather than the API itself.
    """
    try:
        body = resp.json()
    except Exception:
        # A 429 generated by a proxy in front of the API is often not JSON at all.
        body = {}
    if isinstance(body, dict):
        parameters = body.get("parameters")
        if isinstance(parameters, dict) and parameters.get("retry_after") is not None:
            return float(parameters["retry_after"])
    return float(resp.headers.get("Retry-After", DEFAULT_RETRY_AFTER))


def call(
    method: str,
    token: str,
    payload: dict | None = None,
    timeout: int = DEFAULT_TIMEOUT,
    max_retries: int = DEFAULT_MAX_RETRIES,
) -> dict:
    """
    POST one Bot API method and return its `result` field.

    Telegram answers errors with a 4xx *and* a JSON body containing a human
    description ("chat not found", "Unauthorized"). Those descriptions are the
    only useful diagnostic when setup goes wrong, so this reads the body rather
    than letting raise_for_status throw the status code away.
    """
    url = _endpoint(token, method)
    for attempt in range(1, max_retries + 1):
        try:
            resp = requests.post(url, json=payload or {}, timeout=timeout)
        except requests.RequestException as exc:
            # Wrapped rather than propagated so callers have exactly one
            # exception type to handle, and so the failed URL — which carries
            # the bot token — cannot ride out inside a requests exception.
            raise TelegramError(f"{method}: could not reach api.telegram.org ({type(exc).__name__})") from None

        if resp.status_code == 429:
            wait = _retry_after_seconds(resp)
            logger.warning(
                "Telegram rate limit on %s (attempt %s/%s) — sleeping %ss", method, attempt, max_retries, wait
            )
            time.sleep(wait)
            continue

        try:
            body = resp.json()
        except Exception as exc:
            raise TelegramError(f"{method}: HTTP {resp.status_code} with a non-JSON body") from exc

        if not isinstance(body, dict) or not body.get("ok"):
            description = ""
            if isinstance(body, dict):
                description = str(body.get("description", ""))
            raise TelegramError(f"{method}: HTTP {resp.status_code} — {description or 'call rejected'}")

        return body.get("result")

    raise TelegramError(f"{method}: still rate-limited after {max_retries} attempts")


def _clip(text: str) -> str:
    """One message means one message; a 4097-character batch is trimmed, not dropped."""
    if len(text) <= MAX_MESSAGE_CHARS:
        return text
    logger.warning("Telegram message is %s chars — trimming to %s.", len(text), MAX_MESSAGE_CHARS)
    return text[: MAX_MESSAGE_CHARS - len(TRUNCATION_NOTE)] + TRUNCATION_NOTE


def send_message(
    text: str,
    token: str | None = None,
    chat_id: str | None = None,
    call_fn=call,
) -> dict:
    """
    Put `text` in the configured chat as plain text.

    parse_mode is deliberately not set. The proposal strings carry %, +, -, |
    and _ characters that Markdown and HTML modes would either mangle or reject
    outright, and escaping rules have no business leaking back into the
    formatting code in approval_gate.py.

    Raises TelegramError if credentials are missing — callers that want the
    friendly "not configured, carrying on" behaviour check configured() first.
    """
    resolved_token, resolved_chat = credentials(token, chat_id)
    if not resolved_token:
        raise TelegramError("sendMessage: no bot token configured")
    if not resolved_chat:
        raise TelegramError("sendMessage: no chat id configured")

    logger.info("Sending %s chars to Telegram chat %s.", len(text), resolved_chat)
    return call_fn(
        "sendMessage",
        resolved_token,
        {"chat_id": resolved_chat, "text": _clip(text), "disable_web_page_preview": True},
    )


def fetch_updates(
    token: str | None = None,
    limit: int = 100,
    offset: int | None = None,
    poll_timeout: int = 0,
    call_fn=call,
) -> list[dict]:
    """
    Updates for the bot — the raw material for chat-id discovery and for
    reading replies.

    Two modes, both driven by the caller:

    offset=None (the default, used by `--setup` chat-id discovery) consumes nothing.
    Telegram keeps an unacknowledged update for about 24 hours and will keep
    handing it back, which is what setup wants: look, don't disturb.

    offset=N (used by the reply listener) acknowledges everything below N, so a
    poll loop sees each message once instead of re-reading the same "approve 3"
    on every pass. Acknowledging is irreversible — Telegram drops those updates
    — so it is opt-in rather than the default.

    poll_timeout > 0 asks Telegram to hold the connection open until something
    arrives, which is far cheaper than hammering it in a tight loop. The HTTP
    timeout is stretched past it so the client does not give up first.
    """
    resolved_token, _ = credentials(token, "")
    if not resolved_token:
        raise TelegramError("getUpdates: no bot token configured")

    payload: dict = {"limit": limit, "timeout": int(poll_timeout)}
    if offset is not None:
        payload["offset"] = int(offset)

    result = call_fn(
        "getUpdates", resolved_token, payload, timeout=DEFAULT_TIMEOUT + int(poll_timeout)
    )
    return list(result or [])


def next_offset(updates: list[dict]) -> int | None:
    """
    The offset that acknowledges everything in `updates`, or None if empty.

    Telegram's contract is "one past the highest update_id you have handled".
    Computed from the max rather than the last element because the list order
    is not something worth trusting for a value that silently drops messages
    when it is too high.
    """
    ids = [u["update_id"] for u in updates if isinstance(u, dict) and "update_id" in u]
    return max(ids) + 1 if ids else None


def _message_of(update: dict) -> dict | None:
    """The message-ish payload of an update, whichever of the four shapes it is."""
    if not isinstance(update, dict):
        return None
    for key in ("message", "edited_message", "channel_post", "edited_channel_post"):
        candidate = update.get(key)
        if isinstance(candidate, dict):
            return candidate
    return None


def replies_from(updates: list[dict], chat_id: str) -> list[dict]:
    """
    Text messages in `updates` that came from `chat_id`, as
    {"update_id", "text", "name"} — everything else dropped.

    THE FILTER IS THE POINT. A bot's username is public and anyone who finds it
    can message it, so "a reply arrived" and "the owner replied" are different
    claims. Only the configured chat is ever returned, so a stranger's
    "approve all" is not merely rejected downstream — it never becomes a reply
    at all. Nothing reads approvals today, but this is the function that would
    feed them, and it should already be the narrow one.
    """
    wanted = str(chat_id).strip()
    replies = []
    for update in updates:
        message = _message_of(update)
        if not message:
            continue
        chat = message.get("chat")
        if not isinstance(chat, dict) or str(chat.get("id")) != wanted:
            continue
        text = message.get("text")
        if not text:
            continue  # a sticker is not an approval
        name = (
            chat.get("title")
            or " ".join(p for p in (chat.get("first_name"), chat.get("last_name")) if p)
            or chat.get("username")
            or "(no name)"
        )
        replies.append(
            {"update_id": update.get("update_id"), "text": str(text), "name": str(name)}
        )
    return replies


def chat_candidates(updates: list[dict]) -> list[dict]:
    """
    Distinct chats seen in `updates`, newest first, as
    {"chat_id", "name", "kind", "text"}.

    Newest first because the chat the user just messaged from is the one they
    are trying to find; older ones are noise from previous experiments.
    Deduplicated by chat id so a five-message conversation offers one answer,
    not five identical ones.
    """
    seen: dict[str, dict] = {}
    for update in reversed(list(updates)):
        message = _message_of(update)
        if not message:
            continue

        chat = message.get("chat")
        if not isinstance(chat, dict) or chat.get("id") is None:
            continue

        chat_id = str(chat["id"])
        if chat_id in seen:
            continue

        name = (
            chat.get("title")
            or " ".join(p for p in (chat.get("first_name"), chat.get("last_name")) if p)
            or chat.get("username")
            or "(no name)"
        )
        seen[chat_id] = {
            "chat_id": chat_id,
            "name": str(name),
            "kind": str(chat.get("type", "unknown")),
            "text": str(message.get("text", "")),
        }
    return list(seen.values())


def run_setup() -> None:
    """
    One-time chat-id discovery: list every chat the bot has seen recently so
    the right id can be copied into .env as TELEGRAM_CHAT_ID. Read-only —
    fetches updates without acknowledging them (offset=None), so nothing the
    approval gate might later need to read is consumed.
    """
    token, _ = credentials()
    if not token:
        print(MISSING_TOKEN_MESSAGE)
        return

    try:
        chats = chat_candidates(fetch_updates(token))
    except TelegramError as exc:
        print(f"Could not fetch updates: {exc}")
        return

    if not chats:
        print(
            "No chats found. Send your bot any message on Telegram first "
            "(find it by the username you gave @BotFather), then re-run this."
        )
        return

    print("Chats the bot has seen (newest first):\n")
    for chat in chats:
        print(f"  chat_id={chat['chat_id']}  [{chat['kind']}]  {chat['name']}  — last message: {chat['text']!r}")
    print("\nCopy the right chat_id into .env as TELEGRAM_CHAT_ID=...")


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Telegram transport utilities for the approval gate.")
    parser.add_argument(
        "--setup", action="store_true",
        help="List chats the bot has seen, to discover the TELEGRAM_CHAT_ID value.",
    )
    args = parser.parse_args()
    if args.setup:
        run_setup()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
